# Generated by Django 4.0.2 on 2022-02-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_rename_converersion_conversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='if_finished',
            field=models.BooleanField(default=False),
        ),
    ]
