# Generated by Django 4.0.2 on 2022-02-09 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_conversion_if_finished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversion',
            old_name='if_finished',
            new_name='is_finished',
        ),
    ]
